apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: g4v6z0ked-python 
  janus-idp.io/tekton: g4v6z0ked-python
  backstage.io/kubernetes-id: g4v6z0ked-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: g4v6z0ked-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml