apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: g4v6z0ked-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: g4v6z0ked-python 
  name: g4v6z0ked-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: g4v6z0ked-python
    weight: 100 
