apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: g4v6z0ked-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: g4v6z0ked-python 
  name: g4v6z0ked-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: g4v6z0ked-python 
